package com.aws.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

@DynamoDBTable(tableName = "student")
@ApiModel(description = "Details about the student")
public class Student implements Serializable {
    private static final long serialVersionUID = 1L;

    @ApiModelProperty(notes = "Unique Student Id")
    private String studentId;
    @ApiModelProperty(notes = "The Student's first name")
    private String firstName;
    @ApiModelProperty(notes = "The Student's last name")
    private String lastName;
    @ApiModelProperty(notes = "The Student's age")
    private String age;
    private Address address;

    @DynamoDBHashKey(attributeName = "studentId")
    @DynamoDBAutoGeneratedKey
    public String getStudentId() {
        return studentId;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBRangeKey
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBAttribute
    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    @DynamoDBAttribute
    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }
}
